import type { Metadata } from 'next';
import { Roboto, Big_Shoulders } from 'next/font/google';
import './globals.css';

export const bigShoulders = Big_Shoulders({
  variable: '--font-big-shoulders',
  subsets: ['latin'],
});

const robot = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robot.className}`}>{children}</body>
    </html>
  );
}
