import type { Metadata } from 'next';
import Lenis from '@/components/lenis/Lenis';
import { robot } from '@/lib/fonts';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robot.className}`}>
        <Lenis />
        {children}
      </body>
    </html>
  );
}
